version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

commands:
  check_version:
    steps:
      - run:
          name: check version
          command: |
            aws --version

jobs:
  check_version:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - check_version

workflows:
  version: 2
  release-workflow:
    jobs:
      - check_version:
          filters:
            tags:
              only: /.*/
