version: 2.1

orbs:
  sam-cli: circleci/aws-sam-serverless@3.1.0

commands:
  check_version_latest:
    steps:
      - run:
          name: check version
          command: |
            sam --version

  check_version_fix:
    steps:
      - run:
          name: check version
          command: |
            sam --version
jobs:
  check_version_latest:
    executor: sam-cli/default
    steps:
      - checkout
      - sam-cli/install
      - check_version_latest

  check_version_fix:
    executor: sam-cli/default
    steps:
      - checkout
      - sam-cli/install:
          version: v1.31.0
      - check_version_fix

workflows:
  version: 2
  my-workflow:
    jobs:
      - check_version_latest:
          filters:
            tags:
              only: /.*/

      - check_version_fix:
          filters:
            tags:
              only: /.*/
          requires:
            - check_version_latest
